### ISSUE TITLE
Create comment on failure

### ISSUE THREAD

**Issue by tisonkun** [tisonkun/actions-dco#10]
See also [this snippet](https://github.com/databricks/databricks-sql-nodejs/blob/a86e3de34e509b2872d87b06ecb94d1551452253/.github/workflows/dco-check.yml#L8-L25):

```yml
    steps:
      - name: Check for DCO
        id: dco-check
        uses: tisonkun/actions-dco@v1.1
      - name: Comment about DCO status
        uses: actions/github-script@v6
        if: ${{ failure() }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Thanks for your contribution! To satisfy the DCO policy in our \
              [contributing guide](https://github.com/databricks/databricks-sql-nodejs/blob/main/CONTRIBUTING.md) \
              every commit message must include a sign-off message. One or more of your commits is missing this message. \
              You can reword previous commit messages with an interactive rebase (\`git rebase -i main\`).`
            })
```

Perhaps we can introduce an optional config to create a comment on failure with the value.
